import { router, json, error, requireAuth } from '@appdeploy/sdk';
import { db, secrets } from '@appdeploy/sdk';

type Project = { idea: string; name: string; researchQuestion: string; description: string; areas: string[]; questionnaireId?: string; ownerId: string };
type Question = { id: string; text: string; type: string; required: boolean; purpose: string; options?: string[] };
type Section = { id: string; title: string; questions: Question[] };
type Questionnaire = { projectId: string; title: string; description: string; sections: Section[]; publishedSlug?: string; ownerId: string };
type Connection = { ownerId: string; provider: string; model: string; encryptedKey: string; fingerprint: string };
type AgentToken = { ownerId: string; tokenHash: string; prefix: string; createdAt: string; revokedAt?: string };
function randomSlug() { return crypto.randomUUID().replaceAll('-', '').slice(0, 12); }
function b64(bytes: Uint8Array) { let s = ''; for (const b of bytes) s += String.fromCharCode(b); return btoa(s); }
function unb64(s: string) { return Uint8Array.from(atob(s), c => c.charCodeAt(0)); }
async function cryptoKey() { const secret = await secrets.readSecret('APP_ENCRYPTION_KEY'); const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(secret)); return crypto.subtle.importKey('raw', digest, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']); }
async function encrypt(value: string) { const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await cryptoKey(); const body = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(value)); return b64(iv) + '.' + b64(new Uint8Array(body)); }
async function decrypt(value: string) { const [iv, body] = value.split('.'); const key = await cryptoKey(); const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(iv) }, key, unb64(body)); return new TextDecoder().decode(plain); }
async function fingerprint(value: string) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest)).map(x => x.toString(16).padStart(2, '0')).join('').slice(0, 12); }
async function tokenHash(value: string) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest)).map(x => x.toString(16).padStart(2, '0')).join(''); }
function newAgentToken() { const bytes = crypto.getRandomValues(new Uint8Array(32)); return btoa(String.fromCharCode(...bytes)).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', ''); }
async function agentUserId(event: any) { const headers = (event as any)?.headers || {}; const header = headers.authorization || headers.Authorization || ''; const match = String(header).match(/^Bearer (.+)$/i); if (!match) return null; const hash = await tokenHash(match[1]); const r = await db.list<AgentToken>('agent_tokens', { limit: 20, filter: { tokenHash: hash } }); const token = r.items[0]; return token && !token.revokedAt ? token.ownerId : null; }
function mcpJson(body: unknown, status = 200) { return { statusCode: status, headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Authorization, Content-Type, MCP-Protocol-Version, Mcp-Method, Mcp-Name' }, body: JSON.stringify(body) }; }
const MCP_TOOLS = [
  { name: 'create_research_project', title: 'Create research project', description: 'Create a research project from an idea and a chosen research question. The project starts with an empty questionnaire.', inputSchema: { type: 'object', properties: { name: { type: 'string' }, idea: { type: 'string' }, researchQuestion: { type: 'string' }, description: { type: 'string' }, areas: { type: 'array', items: { type: 'string' } } }, required: ['idea', 'researchQuestion'] }, annotations: { destructiveHint: false } },
  { name: 'get_research_project', title: 'Get research project', description: 'Read a research project, its research question, areas, and questionnaire.', inputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'] }, annotations: { readOnlyHint: true } },
  { name: 'develop_research_direction', title: 'Develop research direction', description: 'Turn an initial idea into candidate research questions without prematurely proposing a solution.', inputSchema: { type: 'object', properties: { idea: { type: 'string' } }, required: ['idea'] }, annotations: { readOnlyHint: true } },
  { name: 'add_question', title: 'Add questionnaire question', description: 'Add a question to an existing questionnaire. The agent must explicitly choose the question.', inputSchema: { type: 'object', properties: { questionnaireId: { type: 'string' }, sectionId: { type: 'string' }, text: { type: 'string' }, type: { type: 'string' }, required: { type: 'boolean' }, purpose: { type: 'string' }, options: { type: 'array', items: { type: 'string' } } }, required: ['questionnaireId', 'text'] }, annotations: { destructiveHint: false } },
  { name: 'critique_question', title: 'Critique questionnaire question', description: 'Assess a question for leading wording, solution bias, ambiguity, and research alignment.', inputSchema: { type: 'object', properties: { projectId: { type: 'string' }, text: { type: 'string' }, purpose: { type: 'string' } }, required: ['projectId', 'text'] }, annotations: { readOnlyHint: true } },
  { name: 'analyze_coverage', title: 'Analyze research coverage', description: 'Compare the questionnaire against the research question and investigation areas to identify important gaps.', inputSchema: { type: 'object', properties: { projectId: { type: 'string' } }, required: ['projectId'] }, annotations: { readOnlyHint: true } },
  { name: 'publish_questionnaire', title: 'Publish questionnaire', description: 'Publish a non-empty questionnaire and return its public link.', inputSchema: { type: 'object', properties: { questionnaireId: { type: 'string' } }, required: ['questionnaireId'] }, annotations: { destructiveHint: false } },
  { name: 'get_responses', title: 'Get questionnaire responses', description: 'Retrieve submitted responses for a questionnaire owned by the agent user.', inputSchema: { type: 'object', properties: { questionnaireId: { type: 'string' } }, required: ['questionnaireId'] }, annotations: { readOnlyHint: true } }
];
async function mcpToolCall(userId: string, name: string, args: any) {
  if (name === 'develop_research_direction') return runAI(userId, 'turn an initial idea into researchable questions', 'Initial idea: ' + String(args.idea || '') + '\nPropose three distinct research questions. Keep them exploratory, specific enough to investigate, and free of a proposed solution. Label the strongest candidate and briefly explain why.');
  if (name === 'create_research_project') { const idea = String(args.idea || '').trim(); const researchQuestion = String(args.researchQuestion || '').trim(); if (!idea || !researchQuestion) throw new Error('idea and researchQuestion are required.'); const project: Project = { idea, name: String(args.name || 'Untitled research').trim(), researchQuestion, description: String(args.description || '').trim(), areas: Array.isArray(args.areas) ? args.areas.map(String).filter(Boolean) : [], ownerId: userId }; const [projectId] = await db.add('projects', [project]); if (!projectId) throw new Error('Could not create project.'); const questionnaire: Questionnaire = { projectId, title: project.name + ' Questionnaire', description: 'A research instrument for investigating the question above.', sections: [], ownerId: userId }; const [qid] = await db.add('questionnaires', [questionnaire]); if (!qid) { await db.delete('projects', [projectId]); throw new Error('Could not create questionnaire.'); } const updated = { ...project, questionnaireId: qid }; await db.update('projects', [{ id: projectId, record: updated }]); return { project: { ...updated, id: projectId }, questionnaire: { ...questionnaire, id: qid } }; }
  if (name === 'get_research_project') { const p = await owned<Project>('projects', String(args.projectId || ''), userId); if (!p || !p.questionnaireId) throw new Error('Research project not found.'); const [q] = await db.get<Questionnaire>('questionnaires', [p.questionnaireId]); if (!q) throw new Error('Questionnaire not found.'); return { project: { ...p, id: args.projectId }, questionnaire: { ...q, id: p.questionnaireId } }; }
  if (name === 'add_question') { const q = await owned<Questionnaire>('questionnaires', String(args.questionnaireId || ''), userId); if (!q) throw new Error('Questionnaire not found.'); const sectionId = String(args.sectionId || ''); let sections = q.sections.slice(); let section = sections.find(s => s.id === sectionId); if (!section) { section = { id: crypto.randomUUID(), title: 'Questions', questions: [] }; sections = [...sections, section]; } const question: Question = { id: crypto.randomUUID(), text: String(args.text || '').trim(), type: String(args.type || 'long_text'), required: Boolean(args.required), purpose: String(args.purpose || ''), options: Array.isArray(args.options) ? args.options.map(String).filter(Boolean) : undefined }; if (!question.text) throw new Error('Question text is required.'); section.questions = [...section.questions, question]; await db.update('questionnaires', [{ id: String(args.questionnaireId), record: { ...q, sections } }]); return { questionnaireId: args.questionnaireId, question, sectionId: section.id }; }
  if (name === 'critique_question') { const p = await owned<Project>('projects', String(args.projectId || ''), userId); if (!p) throw new Error('Research project not found.'); return runAI(userId, 'critique one questionnaire question', 'Research question: ' + p.researchQuestion + '\nInvestigation areas: ' + p.areas.join(', ') + '\nQuestion: ' + String(args.text || '') + '\nPurpose: ' + String(args.purpose || '')); }
  if (name === 'analyze_coverage') { const p = await owned<Project>('projects', String(args.projectId || ''), userId); if (!p || !p.questionnaireId) throw new Error('Research project not found.'); const [q] = await db.get<Questionnaire>('questionnaires', [p.questionnaireId]); if (!q) throw new Error('Questionnaire not found.'); return runAI(userId, 'analyze research coverage', 'Research question: ' + p.researchQuestion + '\nAreas: ' + p.areas.join(', ') + '\nQuestionnaire: ' + JSON.stringify(q) + '\nIdentify missing or weak areas and suggest concrete questions to close important gaps.'); }
  if (name === 'publish_questionnaire') { const q = await owned<Questionnaire>('questionnaires', String(args.questionnaireId || ''), userId); if (!q) throw new Error('Questionnaire not found.'); if (!q.sections.some(s => s.questions.length > 0)) throw new Error('Add at least one question before publishing.'); const slug = q.publishedSlug || randomSlug(); const publicRecord = { sourceQuestionnaireId: String(args.questionnaireId), slug, title: q.title, description: q.description, sections: q.sections, publishedAt: new Date().toISOString(), ownerId: userId }; const existing = await db.list<any>('public_questionnaires', { limit: 20, filter: { sourceQuestionnaireId: String(args.questionnaireId) } }); if (existing.items[0]) await db.update('public_questionnaires', [{ id: existing.items[0].id, record: publicRecord }]); else await db.add('public_questionnaires', [publicRecord]); await db.update('questionnaires', [{ id: String(args.questionnaireId), record: { ...q, publishedSlug: slug } }]); return { slug, publicUrl: '/?r=' + slug }; }
  if (name === 'get_responses') { const q = await owned<Questionnaire>('questionnaires', String(args.questionnaireId || ''), userId); if (!q) throw new Error('Questionnaire not found.'); const r = await db.list<any>('responses', { limit: 100, filter: { sourceQuestionnaireId: String(args.questionnaireId) } }); return { responses: r.items }; }
  throw new Error('Unknown MCP tool: ' + name);
}
async function owned<T extends { ownerId: string }>(table: string, id: string, userId: string) { const [record] = await db.get<T & { id: string }>(table, [id]); return record && record.ownerId === userId ? record : null; }
async function callOpenAI(model: string, key: string, system: string, prompt: string) { const r = await fetch('https://api.openai.com/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + key }, body: JSON.stringify({ model, messages: [{ role: 'system', content: system }, { role: 'user', content: prompt }], temperature: 0.2 }) }); if (!r.ok) throw new Error('AI provider request failed (HTTP ' + r.status + ').'); const j = await r.json(); return j.choices?.[0]?.message?.content || ''; }
async function callAnthropic(model: string, key: string, system: string, prompt: string) { const r = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-api-key': key, 'anthropic-version': '2023-06-01' }, body: JSON.stringify({ model, max_tokens: 1600, system, messages: [{ role: 'user', content: prompt }] }) }); if (!r.ok) throw new Error('AI provider request failed (HTTP ' + r.status + ').'); const j = await r.json(); return (j.content || []).map((x: { text?: string }) => x.text || '').join(''); }
async function callGemini(model: string, key: string, system: string, prompt: string) { const r = await fetch('https://generativelanguage.googleapis.com/v1beta/models/' + encodeURIComponent(model) + ':generateContent?key=' + encodeURIComponent(key), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ systemInstruction: { parts: [{ text: system }] }, contents: [{ parts: [{ text: prompt }] }] }) }); if (!r.ok) throw new Error('AI provider request failed (HTTP ' + r.status + ').'); const j = await r.json(); return (j.candidates?.[0]?.content?.parts || []).map((x: { text?: string }) => x.text || '').join(''); }
async function providerCall(c: Connection, system: string, prompt: string) { const key = await decrypt(c.encryptedKey); if (c.provider === 'openai') return callOpenAI(c.model, key, system, prompt); if (c.provider === 'anthropic') return callAnthropic(c.model, key, system, prompt); if (c.provider === 'gemini') return callGemini(c.model, key, system, prompt); throw new Error('Unsupported AI provider.'); }
async function runAI(userId: string, operation: string, prompt: string) { const r = await db.list<Connection>('ai_connections', { limit: 20, filter: { ownerId: userId } }); const c = r.items[0]; if (!c) return { text: 'AI is not connected yet. Add an AI provider connection in Settings, or continue manually.', provider: null, model: null, available: false }; const system = 'You are a rigorous research-methods assistant. Preserve the researcher\'s intent. Do not invent evidence. Avoid leading questions and premature solution framing. Operation: ' + operation + '. Give concise, actionable output.'; return { text: await providerCall(c, system, prompt), provider: c.provider, model: c.model, available: true }; }
export const handler = router({
  'GET /api/projects': [requireAuth(), async ctx => { const r = await db.list<Project>('projects', { limit: 50, filter: { ownerId: ctx.user!.userId } }); return json({ projects: r.items }); }],
  'POST /api/projects': [requireAuth(), async ctx => { const b = ctx.body as Partial<Project>; if (!b.idea?.trim() || !b.researchQuestion?.trim()) return error('An idea and research question are required.', 400); const project: Project = { idea: b.idea.trim(), name: b.name?.trim() || 'Untitled research', researchQuestion: b.researchQuestion.trim(), description: b.description?.trim() || '', areas: Array.isArray(b.areas) ? b.areas.filter(Boolean).map(String) : [], ownerId: ctx.user!.userId }; const [projectId] = await db.add('projects', [project]); if (!projectId) return error('Could not create project.', 500); const questionnaire: Questionnaire = { projectId, title: b.name?.trim() ? b.name.trim() + ' Questionnaire' : 'Research Questionnaire', description: 'A research instrument for investigating the question above.', sections: [], ownerId: ctx.user!.userId }; const [qid] = await db.add('questionnaires', [questionnaire]); if (!qid) { await db.delete('projects', [projectId]); return error('Could not create questionnaire.', 500); } const updatedProject = { ...project, questionnaireId: qid }; await db.update('projects', [{ id: projectId, record: updatedProject }]); return json({ project: { ...updatedProject, id: projectId }, questionnaire: { ...questionnaire, id: qid } }, 201); }],
  'GET /api/projects/:id': [requireAuth(), async ctx => { const p = await owned<Project>('projects', ctx.params.id, ctx.user!.userId); if (!p || !p.questionnaireId) return error('Research project not found.', 404); const [q] = await db.get<Questionnaire>('questionnaires', [p.questionnaireId]); if (!q) return error('Questionnaire not found.', 404); return json({ project: { ...p, id: ctx.params.id }, questionnaire: { ...q, id: p.questionnaireId } }); }],
  'PUT /api/questionnaires/:id': [requireAuth(), async ctx => { const q = await owned<Questionnaire>('questionnaires', ctx.params.id, ctx.user!.userId); if (!q) return error('Questionnaire not found.', 404); const b = ctx.body as Partial<Questionnaire>; const record: Questionnaire = { projectId: q.projectId, title: b.title?.trim() || q.title, description: b.description ?? q.description, sections: Array.isArray(b.sections) ? b.sections : q.sections, publishedSlug: q.publishedSlug, ownerId: q.ownerId }; const [ok] = await db.update('questionnaires', [{ id: ctx.params.id, record }]); if (!ok) return error('Could not save questionnaire.', 500); return json({ questionnaire: { ...record, id: ctx.params.id } }); }],
  'POST /api/questionnaires/:id/publish': [requireAuth(), async ctx => { const q = await owned<Questionnaire>('questionnaires', ctx.params.id, ctx.user!.userId); if (!q) return error('Questionnaire not found.', 404); if (!q.sections.some(s => s.questions.length > 0)) return error('Add at least one question before publishing.', 400); const slug = q.publishedSlug || randomSlug(); const publicRecord = { sourceQuestionnaireId: ctx.params.id, slug, title: q.title, description: q.description, sections: q.sections, publishedAt: new Date().toISOString(), ownerId: q.ownerId }; const existing = await db.list<any>('public_questionnaires', { limit: 20, filter: { sourceQuestionnaireId: ctx.params.id } }); if (existing.items[0]) await db.update('public_questionnaires', [{ id: existing.items[0].id, record: publicRecord }]); else await db.add('public_questionnaires', [publicRecord]); const [ok] = await db.update('questionnaires', [{ id: ctx.params.id, record: { ...q, publishedSlug: slug } }]); if (!ok) return error('Could not publish questionnaire.', 500); return json({ slug }); }],
  'GET /api/ai/connections': [requireAuth(), async ctx => { const r = await db.list<Connection>('ai_connections', { limit: 20, filter: { ownerId: ctx.user!.userId } }); return json({ connections: r.items.map(c => ({ id: c.id, provider: c.provider, model: c.model, fingerprint: c.fingerprint })) }); }],
  'POST /api/ai/connections': [requireAuth(), async ctx => { const b = ctx.body as { provider?: string; model?: string; apiKey?: string }; if (!b.provider || !b.model || !b.apiKey) return error('Provider, model and API key are required.', 400); if (!['openai', 'anthropic', 'gemini'].includes(b.provider)) return error('Unsupported AI provider.', 400); const record: Connection = { ownerId: ctx.user!.userId, provider: b.provider, model: b.model.trim(), encryptedKey: await encrypt(b.apiKey), fingerprint: await fingerprint(b.apiKey) }; const existing = await db.list<Connection>('ai_connections', { limit: 20, filter: { ownerId: ctx.user!.userId, provider: b.provider } }); if (existing.items[0]) await db.update('ai_connections', [{ id: existing.items[0].id, record }]); else await db.add('ai_connections', [record]); return json({ saved: true, provider: record.provider, model: record.model, fingerprint: record.fingerprint }, 201); }],
  'POST /api/ai/develop-research-question': [requireAuth(), async ctx => { try { const b = ctx.body as { idea?: string }; if (!b.idea?.trim()) return error('An idea is required.', 400); return json(await runAI(ctx.user!.userId, 'turn an initial idea into researchable questions', 'Initial idea: ' + b.idea + '\nPropose three distinct research questions. Keep them exploratory, specific enough to investigate, and free of a proposed solution. Label the strongest candidate and briefly explain why.')); } catch (e) { console.error(e); return error(e instanceof Error ? e.message : 'AI request failed.', 502); } }],
  'POST /api/ai/critique-question': [requireAuth(), async ctx => { try { const b = ctx.body as { projectId?: string; question?: Question }; const p = b.projectId ? await owned<Project>('projects', b.projectId, ctx.user!.userId) : null; if (!p || !b.question) return error('Research project and question are required.', 400); return json(await runAI(ctx.user!.userId, 'critique one questionnaire question', 'Research question: ' + p.researchQuestion + '\nInvestigation areas: ' + p.areas.join(', ') + '\nQuestion: ' + b.question.text + '\nPurpose: ' + b.question.purpose)); } catch (e) { console.error(e); return error(e instanceof Error ? e.message : 'AI request failed.', 502); } }],
  'POST /api/ai/generate-questions': [requireAuth(), async ctx => { try { const b = ctx.body as { projectId?: string; researchArea?: string }; const p = b.projectId ? await owned<Project>('projects', b.projectId, ctx.user!.userId) : null; if (!p) return error('Research project is required.', 400); return json(await runAI(ctx.user!.userId, 'generate exploratory questionnaire questions', 'Research question: ' + p.researchQuestion + '\nResearch area: ' + (b.researchArea || p.areas[0] || 'the core research question') + '\nGenerate five candidate questions. For each, state what it investigates. Do not assume a solution.')); } catch (e) { console.error(e); return error(e instanceof Error ? e.message : 'AI request failed.', 502); } }],
  'POST /api/ai/analyze-coverage': [requireAuth(), async ctx => { try { const b = ctx.body as { projectId?: string; researchArea?: string; questionnaire?: Questionnaire }; const p = b.projectId ? await owned<Project>('projects', b.projectId, ctx.user!.userId) : null; if (!p || !b.questionnaire) return error('Research project and questionnaire are required.', 400); return json(await runAI(ctx.user!.userId, 'analyze research coverage', 'Research question: ' + p.researchQuestion + '\nAreas: ' + p.areas.join(', ') + '\nQuestionnaire: ' + JSON.stringify(b.questionnaire) + '\nFocus: ' + (b.researchArea || 'all areas') + '\nIdentify missing or weak areas and suggest concrete questions to close important gaps.')); } catch (e) { console.error(e); return error(e instanceof Error ? e.message : 'AI request failed.', 502); } }],
  'POST /api/agent-tokens': [requireAuth(), async ctx => { const existing = await db.list<AgentToken>('agent_tokens', { limit: 20, filter: { ownerId: ctx.user!.userId } }); for (const x of existing.items) if (!x.revokedAt) await db.update('agent_tokens', [{ id: x.id, record: { ...x, revokedAt: new Date().toISOString() } }]); const token = newAgentToken(); const record: AgentToken = { ownerId: ctx.user!.userId, tokenHash: await tokenHash(token), prefix: token.slice(0, 8), createdAt: new Date().toISOString() }; const [id] = await db.add('agent_tokens', [record]); if (!id) return error('Could not create agent access token.', 500); return json({ token, id, prefix: record.prefix, mcpEndpoint: '/mcp' }, 201); }],
  'GET /api/agent-tokens': [requireAuth(), async ctx => { const r = await db.list<AgentToken>('agent_tokens', { limit: 20, filter: { ownerId: ctx.user!.userId } }); return json({ tokens: r.items.filter(x => !x.revokedAt).map(x => ({ id: x.id, prefix: x.prefix, createdAt: x.createdAt })) }); }],
  'DELETE /api/agent-tokens/:id': [requireAuth(), async ctx => { const x = await owned<AgentToken>('agent_tokens', ctx.params.id, ctx.user!.userId); if (!x) return error('Agent token not found.', 404); await db.update('agent_tokens', [{ id: ctx.params.id, record: { ...x, revokedAt: new Date().toISOString() } }]); return json({ revoked: true }); }],
  'POST /api/mcp/test': [requireAuth(), async () => json({ ok: true, protocolVersion: '2026-07-28', toolCount: MCP_TOOLS.length, tools: MCP_TOOLS.map(t => t.name) })],
  'GET /.well-known/oauth-protected-resource': [async () => json({ resource: '/mcp', authorization_servers: [], bearer_methods_supported: ['header'], note: 'This deployment uses user-scoped agent tokens. Full OAuth discovery can be added when an OAuth authorization server is configured.' })],
  'POST /mcp': [async ctx => { const userId = await agentUserId(ctx.event); const body = ctx.body as any; const id = body?.id ?? null; if (!userId) return mcpJson({ jsonrpc: '2.0', id, error: { code: -32001, message: 'Unauthorized. Provide a valid agent bearer token.' } }, 401); const method = String(body?.method || ''); if (method === 'server/discover') return mcpJson({ jsonrpc: '2.0', id, result: { protocolVersion: '2026-07-28', serverInfo: { name: 'Research Workspace MCP', version: '1.0.0' }, capabilities: { tools: {} } } }); if (method === 'tools/list') return mcpJson({ jsonrpc: '2.0', id, result: { tools: MCP_TOOLS, ttlMs: 60000, cacheScope: 'private' } }); if (method === 'tools/call') { const name = String(body?.params?.name || ''); try { const result = await mcpToolCall(userId, name, body?.params?.arguments || {}); return mcpJson({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text: JSON.stringify(result) }], structuredContent: result } }); } catch (e) { return mcpJson({ jsonrpc: '2.0', id, result: { isError: true, content: [{ type: 'text', text: e instanceof Error ? e.message : 'Tool failed.' }] } }); } } return mcpJson({ jsonrpc: '2.0', id, error: { code: -32601, message: 'Method not found.' } }, 404); }],
  'GET /api/public/questionnaires/:slug': [async ctx => { const r = await db.list<any>('public_questionnaires', { limit: 20, filter: { slug: ctx.params.slug } }); const q = r.items[0]; if (!q) return error('Questionnaire not found.', 404); return json({ questionnaire: { title: q.title, description: q.description, sections: q.sections, slug: q.slug } }); }],
  'POST /api/public/questionnaires/:slug/responses': [async ctx => { const r = await db.list<any>('public_questionnaires', { limit: 20, filter: { slug: ctx.params.slug } }); const q = r.items[0]; if (!q) return error('Questionnaire not found.', 404); const b = ctx.body as { answers?: Record<string, unknown> }; if (!b.answers || typeof b.answers !== 'object') return error('Answers are required.', 400); const [rid] = await db.add('responses', [{ publicQuestionnaireId: q.id, sourceQuestionnaireId: q.sourceQuestionnaireId, answers: b.answers, submittedAt: new Date().toISOString() }]); if (!rid) return error('Could not record response.', 500); return json({ responseId: rid }, 201); }],
  'GET /api/questionnaires/:id/responses': [requireAuth(), async ctx => { const q = await owned<Questionnaire>('questionnaires', ctx.params.id, ctx.user!.userId); if (!q) return error('Questionnaire not found.', 404); const r = await db.list<any>('responses', { limit: 100, filter: { sourceQuestionnaireId: ctx.params.id } }); return json({ responses: r.items }); }],
  'GET /api/questionnaires/:id/responses/export': [requireAuth(), async ctx => { const q = await owned<Questionnaire>('questionnaires', ctx.params.id, ctx.user!.userId); if (!q) return error('Questionnaire not found.', 404); const r = await db.list<any>('responses', { limit: 100, filter: { sourceQuestionnaireId: ctx.params.id } }); const rows = ['response_id,submitted_at,answers']; for (const x of r.items) { const answers = JSON.stringify(x.answers).replaceAll('"', '""'); rows.push('"' + x.id + '","' + x.submittedAt + '","' + answers + '"'); } return json({ csv: rows.join('\n'), filename: 'responses.csv' }); }],
  'GET /api/_healthcheck': [async () => json({ message: 'Success' })]
});
